import { StyleSheet } from 'react-native';

import { Colors } from '../../constants/colors';
import { fonts, radius } from '../../constants/layout';

export const authFormStyles = StyleSheet.create({
  flex: { flex: 1, backgroundColor: Colors.black },
  container: {
    flexGrow: 1,
    backgroundColor: Colors.black,
    paddingHorizontal: 24,
    justifyContent: 'center',
  },
  heading: {
    fontSize: 26,
    fontWeight: '800',
    fontFamily: fonts.display,
    color: Colors.white,
    textTransform: 'uppercase',
    marginBottom: 8,
    textAlign: 'center',
  },
  subheading: {
    fontSize: 13,
    color: Colors.grey1,
    marginBottom: 24,
    textAlign: 'center',
  },
  field: { marginBottom: 12 },
  label: {
    fontSize: 11,
    fontWeight: '700',
    fontFamily: fonts.display,
    color: Colors.grey1,
    marginBottom: 6,
    textTransform: 'uppercase',
    letterSpacing: 0.1,
  },
  input: {
    backgroundColor: Colors.surface2,
    borderRadius: radius.input,
    paddingHorizontal: 14,
    paddingVertical: 13,
    fontSize: 14,
    color: Colors.white,
    borderWidth: 1,
    borderColor: Colors.border,
  },
  inputError: {
    borderColor: Colors.red,
  },
  errorText: {
    color: Colors.red,
    fontSize: 12,
    marginTop: 6,
  },
  submitButton: {
    backgroundColor: Colors.yellow,
    paddingVertical: 16,
    borderRadius: radius.button,
    alignItems: 'center',
    marginTop: 20,
    minHeight: 52,
    justifyContent: 'center',
  },
  submitButtonDisabled: {
    opacity: 0.7,
  },
  submitButtonText: {
    color: '#000000',
    fontWeight: '800',
    fontSize: 15,
    fontFamily: fonts.display,
    textTransform: 'uppercase',
    letterSpacing: 0.06,
  },
  tabRow: {
    flexDirection: 'row',
    backgroundColor: Colors.surface,
    borderRadius: 20,
    padding: 4,
    marginBottom: 24,
  },
  tabButton: { flex: 1, paddingVertical: 12, alignItems: 'center', borderRadius: 16 },
  tabActive: { backgroundColor: Colors.yellow },
  tabText: { color: Colors.grey1, fontWeight: '700' },
  tabTextActive: { color: '#000000' },
  forgotText: {
    color: Colors.yellow,
    fontSize: 12,
    fontWeight: '600',
    marginBottom: 18,
    textAlign: 'right',
    marginTop: 8,
  },
  infoText: {
    color: Colors.grey1,
    fontSize: 12,
    marginBottom: 12,
  },
  googleButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    backgroundColor: Colors.surface2,
    borderRadius: radius.button,
    paddingVertical: 14,
    marginTop: 14,
    borderWidth: 1,
    borderColor: Colors.border,
  },
  googleButtonText: {
    color: Colors.white,
    fontWeight: '700',
    fontSize: 14,
  },
  demoButton: {
    backgroundColor: Colors.yellow,
    borderRadius: radius.button,
    paddingVertical: 14,
    marginTop: 18,
    alignItems: 'center',
  },
  demoButtonText: { color: '#000000', fontWeight: '700', fontSize: 13 },
});
