INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Felix Kyei',6,'GK',16,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Adams Abdul Jabal',6,'GK',12,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Yakubu Saeed',6,'GK',1,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Yaw Osei',6,'DEF',41,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Prince Amponsah',6,'DEF',NULL,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Desmond Baffoe',6,'DEF',3,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Yussif Mubarik',6,'DEF',4,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Jacob Mensah',6,'DEF',48,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Rich Sackey',6,'DEF',23,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Kofi Asmah',6,'DEF',24,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Fatawu Sulemana',6,'DEF',21,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Paul Yeboah',6,'DEF',50,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Ebenezer Nkrumah',6,'DEF',13,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Victor Oduro',6,'DEF',15,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Prosper Boakye Owusu',6,'MID',NULL,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Fuzy Taylor',6,'MID',5,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Azariah Fordjour',6,'MID',NULL,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Richard Owusu',6,'MID',27,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Richard Appiah',6,'MID',40,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Salim Adams',6,'MID',35,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Manuel Mantey',6,'MID',8,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Godknows Dzakpasu',6,'MID',28,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Ebenezer Ackahbi',6,'MID',7,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Prince Owusu',6,'MID',32,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Emmanuel Owusu',6,'MID',31,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Kelvin Nkrumah',6,'FWD',17,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Nana Kofi Babil',6,'FWD',20,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Bernardinho Tetteh',6,'FWD',11,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Derrick Fordjour',6,'FWD',10,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Abdul Salam',6,'FWD',36,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Kelvin Obeng',6,'FWD',18,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Kingsley Braye',6,'FWD',19,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('David Boison',6,'FWD',NULL,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Mohammed Rahaman',6,'FWD',NULL,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Ibrahim Nurudeen',6,'FWD',9,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Emmanuel Kobi',5,'GK',1,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Jonathan Annobil Joy',5,'GK',NULL,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Kwadwo Bonsu',5,'GK',16,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Ernest Kussi',5,'GK',22,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Gideon Anaba',5,'DEF',5,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Kelvin Oppong',5,'DEF',4,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Vincent Atinga',5,'DEF',21,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Emmanuel Ankrah',5,'DEF',14,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Yakubu Haqq',5,'DEF',25,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Edward Agyemang',5,'DEF',23,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Samuel Acheampong',5,'DEF',32,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Bright Boakye Kyereh',5,'DEF',26,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Kotey Richard Amon',5,'MID',19,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Philip Ofori',5,'MID',24,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Foster Agyei',5,'MID',11,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Justice Arthur',5,'MID',38,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Emmanuel Kojo Addy',5,'MID',NULL,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Isaac Adjei Adjetey',5,'MID',28,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Emmanuel Kontor',5,'MID',18,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Emmanuel Fosu Kyei',5,'MID',6,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Francis Twene',5,'MID',8,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Rafiu Ibrahim',5,'MID',15,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Maccarthy Appiah',5,'MID',17,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Barimah Baah',5,'FWD',40,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Emmanuel Agyei',5,'FWD',12,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Emmanuel Boateng Agyenim',5,'FWD',2,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Samuel Attah Kumi',5,'FWD',10,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Razack Sanou',5,'FWD',9,NULL,'AVAILABLE','Burkina Faso');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Sampson Eduku',5,'FWD',3,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Bernard Kesse',5,'FWD',30,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Michael Nkoah',5,'FWD',35,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Godfred John Arthur',5,'FWD',20,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Augustine Boakye',5,'FWD',33,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Prince Opoku Agyemang',5,'FWD',37,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Abdul Farouk Amoaful',5,'FWD',39,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Benjamin Asare',3,'GK',16,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Solomon Agbasi',3,'GK',1,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Sharif Shuaib',3,'GK',33,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Baba Adamu',3,'DEF',26,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Albert Amanfo Kwasi',3,'DEF',34,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Ali Mohammed',3,'DEF',4,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Kelvin Osei Asibey',3,'DEF',5,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('David Oppong Afrane',3,'DEF',15,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Emmanuel Amankwah',3,'DEF',12,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Ransford Mensah',3,'DEF',13,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Dennis Korsah',3,'DEF',NULL,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Yahaya Adraman',3,'DEF',24,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Isaac Frimpong',3,'DEF',50,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Abdul Karim',3,'MID',18,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Theophilus Collison',3,'MID',8,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Kwesi Asmah',3,'MID',25,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Gordon Cudjoe',3,'MID',37,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Raphael Amponsah',3,'MID',6,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Stephen Appiah Asare',3,'MID',20,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Mohammed Hussein',3,'MID',14,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('George Paaku',3,'MID',23,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Martin Karikari',3,'MID',11,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Rocky Dwamena',3,'MID',36,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Ramzy Yussif',3,'MID',41,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Mawuli Wayo',3,'FWD',7,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Enock Asubonteng',3,'FWD',32,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Yaw Amankwa Baafi',3,'FWD',35,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Hamza Issah',3,'FWD',17,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Frank Abora Duku',3,'FWD',9,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Asamoah Boateng Afriyie',3,'FWD',NULL,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Prince Kwabena Owusu',3,'FWD',10,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Abdul-Aziz Adam',3,'FWD',29,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Gidios Aseako',15,'GK',1,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Godfred Amoah',15,'GK',NULL,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Osman Wahabu',15,'GK',16,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Al-Hajj Oumar Nauffal',15,'DEF',2,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Desmond Dekpe',15,'DEF',20,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Richard Mensah',15,'DEF',NULL,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Francis Danso',15,'DEF',22,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Wisdom Appasu Lawoe',15,'DEF',25,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Christian Owusu',15,'DEF',4,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Izdeen Mohammed',15,'DEF',3,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Ebenezer Adade',15,'DEF',23,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Issahak Fuseini',15,'DEF',26,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Jonathan Nemorden',15,'MID',17,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Kelvin Ahiable',15,'MID',28,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Okyere Isaac',15,'MID',6,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('David Amuzu',15,'MID',14,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Emmanuel Yeboah Danquah',15,'MID',15,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Nicholas Asante',15,'MID',27,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Asante Oppong',15,'MID',37,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Thuair Dhaud',15,'MID',44,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Seidu Suraj',15,'MID',10,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Yaovi Chris Guede',15,'MID',21,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Adams Aminu',15,'MID',8,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Clement Boahen',15,'FWD',NULL,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Aziz Issah',15,'FWD',NULL,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Yaro Isaac',15,'FWD',29,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Musibau Aziz',15,'FWD',NULL,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('John Antwi',15,'FWD',11,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Abdul Razak Salifu',15,'FWD',35,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Benjamin Bature',15,'FWD',NULL,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Ibrahim Osman',15,'FWD',NULL,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Baboulin Yves Kolani',15,'FWD',7,NULL,'AVAILABLE','Togo');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Charles Nan Kobina Bartels',15,'FWD',19,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Ernest Appiah',15,'FWD',30,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Godfred Sarpong',15,'FWD',31,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Blabala Bamon',15,'FWD',36,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Mohammed Shaban Nazir',15,'FWD',38,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Zakari Musah',4,'GK',16,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Kofi Baah',4,'GK',22,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Richard Baidoo',4,'GK',NULL,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Shaibu Rafique Issah',4,'GK',1,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Sabi Acquah Ferdinand',4,'GK',40,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Roland Grippman',4,'DEF',23,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Joseph Senkyire',4,'DEF',28,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Kofi Agbesimah',4,'DEF',25,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Ebenezer Acquah',4,'DEF',30,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('James Sewornu',4,'DEF',32,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Isaac Afful',4,'DEF',17,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Emmanuel Adu Siaw',4,'DEF',33,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Samuel Tetteh Mensah',4,'DEF',2,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Akwasi Sarpong',4,'MID',14,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Kwaku Owusu',4,'MID',4,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Abdul Latif',4,'MID',6,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Samed Kyei',4,'MID',5,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Enoch Afful',4,'MID',NULL,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Augustine Kofi Ofori',4,'MID',8,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Napari Iddrisu',4,'MID',11,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Dramani Awuah',4,'MID',10,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Emmanuel Essien',4,'MID',24,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Baba Kushibo',4,'MID',NULL,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Solomon Agyei',4,'MID',15,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Felix Koduah Junior',4,'MID',13,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Francis Gyetuah',4,'FWD',9,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Christian Agyenim Boateng',4,'FWD',19,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Isaac Baffoe',4,'FWD',7,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Emmanuel Mamah',4,'FWD',20,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Osman Zakaria',4,'FWD',18,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Mohammed Alhassan Mankuyeli',4,'FWD',29,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Gabriel Osei',4,'FWD',31,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Clinton Kumi',4,'FWD',26,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Benedict Afull',4,'FWD',34,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Osei Prince',1,'GK',41,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Massawudu Inusah',1,'GK',1,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Gregory Obeng Sekyere',1,'GK',16,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Desmond Obeng',1,'DEF',30,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Richard Yeboah',1,'DEF',36,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Stephen Badu',1,'DEF',15,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Alex Boakye',1,'DEF',20,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Samuel Kuffour',1,'DEF',44,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Abubakar Adams',1,'DEF',17,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('William Dankyi',1,'DEF',12,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Remember Adomako Boateng',1,'DEF',21,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Elvis Addo',1,'DEF',13,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Stephen Kwakye',1,'DEF',23,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Raymond Agyemang',1,'MID',4,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Maxwell Arthur',1,'MID',5,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Seidu Saana',1,'MID',8,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Godfred Boakye',1,'MID',25,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Samuel Owusu Ansah',1,'MID',29,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Salim Uzair Baafada',1,'MID',40,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Silas Kyeremeh',1,'MID',6,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Abdul-Aziz Nurudeen',1,'MID',24,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Gideon Asante Yeboah',1,'MID',35,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Sam Adams',1,'MID',7,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Richard Afriyie',1,'MID',37,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Hensen Anponsa',1,'MID',11,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Patrick Mensah',1,'FWD',18,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Prince Otubua',1,'FWD',33,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Daniel Awuni',1,'FWD',26,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Daouda Sidibé',1,'FWD',27,NULL,'AVAILABLE','Burkina Faso');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Benjamin Tsivanyo',1,'FWD',39,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Charles Gyamfi Kamara',1,'FWD',14,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Emmanuel Marfo',1,'FWD',9,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Mezack Afriyie',1,'FWD',19,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Bright Adjei',1,'FWD',10,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Mohammed Bamba',1,'FWD',NULL,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Kofi Asante',1,'FWD',32,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Eric Ofori-Antwi',8,'GK',16,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Adu Emmanuel',8,'GK',12,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Joshua Addai',8,'GK',30,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Alfred Owusu',8,'GK',NULL,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Richard Osei',8,'DEF',14,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Zidane Osman',8,'DEF',NULL,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Kennedy Kofi Mensah',8,'DEF',24,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Emmanuel Ofosu',8,'DEF',33,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Mohammed Seidu',8,'DEF',15,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Michael Mensah Awuah',8,'DEF',35,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Samuel Amofa',8,'DEF',2,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Kofi Tanab Oxborn',8,'DEF',4,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Morrison Anokye',8,'DEF',NULL,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Benjamin Abaidoo',8,'DEF',3,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Prince Anane',8,'DEF',19,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Augustine Agyapong',8,'DEF',26,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Kuffour Edwin Asamoah',8,'DEF',8,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Benjamin Awuah Achempong',8,'DEF',13,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Kwesi Sorotu Badori',8,'MID',NULL,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Vincent Klu Adjei',8,'MID',27,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Samuel Tenedu',8,'MID',36,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Samed Nasri Musah',8,'MID',11,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Charles Agyemang',8,'MID',17,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Flavien Kongoza',8,'MID',28,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('William Bediako',8,'MID',29,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Mohammed Jackson Asante',8,'MID',32,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Fataho Nerie',8,'MID',37,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Augustine Henneh',8,'MID',45,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Johnson Osei',8,'MID',42,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Jonah Attuquaye',8,'FWD',20,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Abubakari Seidu',8,'FWD',40,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Kofi Patric Ansu',8,'FWD',7,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Marvin Owusu',8,'FWD',9,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Faisal Shaibu',8,'FWD',25,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Emmanuel Sarpong',8,'FWD',NULL,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Emmanuel Kwakye',8,'FWD',5,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Rahman Abdul',8,'FWD',39,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Johnson Amuzu',8,'FWD',41,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Kwasi Ofosu',8,'FWD',NULL,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Mohamed Camara',2,'GK',16,NULL,'AVAILABLE','Guinea');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Dari Aziz Haruna',2,'GK',1,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Benjamin Twum',2,'GK',13,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Fatao Seidu',2,'GK',NULL,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Avoka Kwasi Vitus',2,'DEF',NULL,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Samba O''Neil',2,'DEF',6,NULL,'AVAILABLE','Nigerien/Congolese');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Musa Hamzata',2,'DEF',5,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Henry Ansu',2,'DEF',15,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Fuseini Zackaria',2,'DEF',21,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Joseph Ablorh',2,'DEF',22,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Patrick Asiedu',2,'DEF',17,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Francis Acquah',2,'DEF',3,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Inusah Adam',2,'DEF',23,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Joseph Amoah',2,'DEF',26,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Yakubu Dogo',2,'DEF',42,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Lord Amoah',2,'DEF',27,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Emmanuel Kotei',2,'DEF',43,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Shayibu Abubakari',2,'DEF',2,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Lord Hilary Adabo',2,'MID',8,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Prince Badu',2,'MID',44,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Andrews Ntim',2,'MID',25,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Solomon Kwaku Sah',2,'MID',NULL,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Hubert Gyau',2,'MID',12,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Seth Kwadwo',2,'MID',20,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Emmanuel Antwi',2,'MID',10,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Walid Fuseini',2,'MID',28,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Philip Amoh',2,'MID',4,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Yahaya Baba',2,'MID',19,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Bernard Somuah',2,'FWD',NULL,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Morifing Donzo',2,'FWD',9,NULL,'AVAILABLE','Guinea');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Saaka Dauda',2,'FWD',11,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Elvis Baffour',2,'FWD',NULL,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Johnson Owusu',2,'FWD',45,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Peter Amidu Acquah',2,'FWD',30,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Kwame Opoku',2,'FWD',7,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Isaac Mintah',2,'FWD',NULL,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Jordan Amissah',2,'FWD',29,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Ganiu Mohammed Abdul',9,'GK',12,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Daniel Afadzwu',9,'GK',16,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Kelvin Kofi Saaba',9,'GK',95,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Joseph Bekoe',9,'DEF',20,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Sharif Bashiru',9,'DEF',47,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Faisal Gariba',9,'DEF',3,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Abdul-Raman Yaya',9,'DEF',21,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Joseph Quansah',9,'DEF',6,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Nurudeen Yussif Mohammed',9,'DEF',57,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Alhassan Ali',9,'DEF',30,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Mohammed Abubakar',9,'DEF',NULL,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Fatawu Mohammed',9,'DEF',2,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Malik Abubakar',9,'MID',13,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Mohammed Awal Alhassan',9,'MID',33,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Abdulai Zakari',9,'MID',50,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Philip Adom',9,'MID',35,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Mohammed Asigre Sulemana',9,'MID',23,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Prince Arthur',9,'MID',42,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Moses Parker',9,'MID',48,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Abedi Karim',9,'MID',70,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Hafiz Abdulai',9,'MID',18,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Jibril Nurudeen',9,'MID',17,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Godfred Abban',9,'MID',10,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Kassim Sule',9,'MID',27,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Tumelo Makha',9,'MID',45,NULL,'AVAILABLE','Lesotho');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Fidaus Mohammed',9,'MID',8,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Evans Osei-Wusu',9,'FWD',90,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Abdul-Shakun Abubakari',9,'FWD',7,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Richard Berko',9,'FWD',34,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Eric Antwi Konadu',9,'FWD',11,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Bless Ege',9,'FWD',NULL,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Gideon Boateng',9,'FWD',26,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Felix Mortu',9,'FWD',9,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Solomon Aboagye',9,'FWD',32,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Olivier Adom',9,'FWD',44,NULL,'AVAILABLE','Cote d''Ivoire');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Danlad Nuhu',9,'FWD',77,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Benjamin Asiedu Kwesi',7,'GK',13,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Elvis Yeboah',7,'GK',NULL,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Emmanuel Anning',7,'GK',1,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Dennis Votere',7,'GK',16,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Abdul Razak Alhassan',7,'DEF',15,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('James Yeboah',7,'DEF',14,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Boa-At Regain',7,'DEF',22,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Atta Derrick Afriyie',7,'DEF',32,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Baba Moro Abdulai',7,'DEF',35,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Foster Gyamfi',7,'DEF',53,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Emmanuel Ababio',7,'DEF',25,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Yaw Acheampong',7,'DEF',5,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Adams Sanut',7,'DEF',3,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Emmanuel Ampiah',7,'DEF',33,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Charles Owusu',7,'DEF',NULL,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Rasco Abassah London',7,'MID',6,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Emmanuel Sefah',7,'MID',28,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Richard Dwamena',7,'MID',50,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Kofi Tompuo',7,'MID',51,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Christian Tonah',7,'MID',43,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Frank Amankwah',7,'MID',23,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Isaiah Nyarko',7,'MID',17,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Augustine Okrah',7,'MID',10,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Emmanuel Abban',7,'FWD',11,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Mohammed Aminu',7,'FWD',77,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Darlvin Yeboah',7,'FWD',9,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Yaw Annor',7,'FWD',7,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Augustine Afranie Mensah',7,'FWD',18,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Foster Sakitey',7,'FWD',27,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Godfred Yawson',7,'FWD',39,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Samuel Ayinebire Atubga',7,'FWD',2,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Rueben Owusu Boadu',7,'FWD',19,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Amadu Abdulai',7,'FWD',21,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Samuel Okai',7,'FWD',24,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Kelvin Appiah',7,'FWD',29,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Kabu Agyemang Raymond',7,'FWD',30,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Kwame Aziz',16,'GK',13,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Godwin Ametefe',16,'GK',26,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Michael Blankson',16,'GK',NULL,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Francis Lotsa',16,'GK',1,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Sam-An Mohammed',16,'DEF',18,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Musah Amevor',16,'DEF',NULL,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Frank Dongballe',16,'DEF',45,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Sahadu Sulley',16,'DEF',70,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Lord Xorse Kudzinya',16,'DEF',77,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Prince Asante',16,'DEF',88,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Edwards Elijah',16,'DEF',NULL,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Nicholas Mensah',16,'DEF',10,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Labaran Majeed Alidu',16,'DEF',23,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Foster Twum',16,'DEF',12,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Emmanuel Sanja',16,'DEF',27,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Ridwan Ali',16,'DEF',21,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Meshack Sowah Adjetey',16,'MID',2,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Ibrahim Larbi',16,'MID',5,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Aminu Alhassan',16,'MID',NULL,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Silvanus Atta',16,'MID',NULL,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Maxwell Kwaku Sensah',16,'MID',NULL,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Richmond Ocran',16,'MID',8,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Emmanuel Atta Frimpong',16,'MID',19,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Alex Yamoah',16,'MID',34,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Nana Kwesi Amoah',16,'MID',51,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Kingsley Appiah',16,'MID',15,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Daniel Yemoh',16,'MID',7,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Mohammed Alidu',16,'MID',29,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Abdul Rauf Sulemana',16,'MID',41,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Edmond Asante',16,'MID',55,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Joseph Cudjoe',16,'MID',84,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Emmanuel Kyei Baffour',16,'MID',20,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Joshua Kwame Rhule',16,'FWD',3,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Dickson Afoakwa',16,'FWD',17,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Sherif Mohammed Iddrisu',16,'FWD',24,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Obed Bentum',16,'FWD',NULL,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Evans Akuaku',16,'FWD',9,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('George Tei Nagadzi',16,'FWD',44,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Dubi Kassi Tayi',12,'GK',1,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Wahab Abubakar',12,'GK',16,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Patrick Appiah',12,'GK',41,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Prince Asempa',12,'GK',42,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Jeff Tiero Eduku',12,'DEF',NULL,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Kingsford Baffoe',12,'DEF',12,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Emmanuel Brace',12,'DEF',14,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Abdul Dagbatey Basit',12,'DEF',31,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Boniface Blay',12,'DEF',33,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Moses Author',12,'DEF',4,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Jacob Boazee',12,'DEF',27,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Sadat Zumah Ibrahim',12,'DEF',30,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Emmanuel Kwame',12,'DEF',37,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Francis Asante',12,'DEF',55,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Issah Yakubu',12,'MID',22,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Koffie Hagan',12,'MID',13,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Abubakar Konda Adams',12,'MID',15,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Elim Jonnie Minimsaah',12,'MID',28,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Lawrence Gadeseh',12,'MID',36,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Francis Oteng',12,'MID',6,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('George Kissi Nana',12,'MID',32,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Enis Boadi',12,'MID',5,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Gabriel Appiah',12,'MID',8,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Quaison Kofi Gideon',12,'MID',25,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Simba Sylvester',12,'MID',77,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Francis Adjei',12,'MID',NULL,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Prince Tweneboah',12,'FWD',19,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Augustine Owusu',12,'FWD',NULL,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Patrick Ocran',12,'FWD',NULL,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Prince Opoku',12,'FWD',3,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Victor Aidoo',12,'FWD',7,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Richmond Somiah',12,'FWD',10,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Cosmos Marfo',12,'FWD',17,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Kojo Mahama',12,'FWD',20,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Mathew Mensah',12,'FWD',21,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Prince Gamor',12,'FWD',35,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Alexander Cobbinah',12,'FWD',44,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Bismark Teye',12,'FWD',68,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Zulka Masawudu',14,'GK',22,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Frank Boateng',14,'GK',31,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Eddem Ofosu',14,'GK',12,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Abdulai Kadel',14,'GK',1,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Richmond Nsiah Coka',14,'DEF',24,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Claude Shooting Borrtey',14,'DEF',19,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Prince Mensah',14,'DEF',NULL,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Francis Obubuafo Tetteh',14,'DEF',NULL,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Fuseini Ibrahim',14,'DEF',6,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Antwi Dacosta',14,'DEF',NULL,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Issah Nyaabila',14,'DEF',13,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Rahman Rurf Abdul',14,'DEF',15,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Sule Muntalla',14,'DEF',NULL,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Mobarick Zakari Abdul',14,'DEF',34,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Mathias Amegbe',14,'DEF',25,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Abdul Ganiyu Muftaw',14,'MID',5,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Agyemang Kingsford',14,'MID',2,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Ramzy Abubakar',14,'MID',8,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Richmond Ampong',14,'MID',3,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Randolf Akwasi Nti',14,'MID',4,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Vincent Mobilla',14,'MID',17,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Emmanuel Agyei',14,'MID',23,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('David Ayene Kofi',14,'MID',36,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Richard Oppong',14,'MID',27,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Joseph Mensah',14,'MID',7,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('John Atta Junior Afram',14,'MID',20,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Richmond Opoku',14,'MID',40,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Huseine Issah',14,'FWD',11,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Lawrence Owusu',14,'FWD',26,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Samuel Prempeh',14,'FWD',21,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Croster Obour Adu',14,'FWD',NULL,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Francis Andy Kumi',14,'FWD',9,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Pius Asante Yeboah',14,'FWD',50,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Lawrence Osei',18,'GK',1,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Samson Obeng Adade',18,'GK',NULL,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Jayson Nettey',18,'GK',16,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Danso Wiredu Mensah',18,'GK',44,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Odartey Lamptey',18,'GK',50,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Abdullah Musah',18,'DEF',NULL,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Ruben Hennessy',18,'DEF',4,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Ebenezer Abban',18,'DEF',5,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Fawzi Ali',18,'DEF',17,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Macaulley Kojo Kuma',18,'DEF',20,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Esias Kwesi Acquah',18,'DEF',45,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Bismark Anim',18,'DEF',14,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Kwesi Pong',18,'DEF',10,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('George Osei',18,'DEF',28,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Atta Kusi',18,'DEF',37,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Etse Dogli',18,'MID',3,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Humaid Fuseini',18,'MID',2,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Faisal James Tsorhwe',18,'MID',30,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Yaw Danso',18,'MID',36,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Dickson Sakabutu',18,'MID',NULL,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Anthony Owusu',18,'MID',24,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Denis Hutor',18,'MID',26,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Seedorf Asante',18,'MID',29,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Ishmael Addo',18,'MID',6,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Moses Ayidem',18,'FWD',15,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Chauncy Freeman',18,'FWD',22,NULL,'AVAILABLE','Liberia');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Paul Attah Agyei',18,'FWD',7,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Michael Ephson',18,'FWD',23,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Kwadwo Obeng Junior',18,'FWD',11,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Benson Kofi Yeboah',18,'FWD',NULL,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Abednego Tetteh',18,'FWD',9,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Kelvin Asenso',18,'FWD',18,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Sheriff Alabani',18,'FWD',35,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Clement Aryee',13,'GK',12,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Michael Appiah',13,'GK',NULL,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Derrick Prince Kofi',13,'GK',1,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Zayat Bubakari',13,'DEF',5,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Daniel Sowah',13,'DEF',24,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('John Andoh',13,'DEF',38,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Maxwell Kofi Yeboah',13,'DEF',NULL,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Baffoe Stephen',13,'DEF',NULL,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Suleman Yakubu Omar',13,'DEF',8,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Oscar Mensah',13,'DEF',15,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Kwadwo Opoku-Gyamfi',13,'DEF',21,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Hafiz Alhassan',13,'DEF',29,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Kojo Isaac Inkoom',13,'DEF',NULL,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Roland Leveh',13,'DEF',3,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Derrick Assiamah',13,'DEF',20,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Abdul Aziz',13,'DEF',30,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Clement Tutu',13,'DEF',6,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Ayikabia Solomon Anyork Nereba',13,'MID',10,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Frank Awere',13,'MID',14,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Shadrack Arthur',13,'MID',27,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Benjamin Adjei',13,'MID',28,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('William Danquah',13,'MID',45,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Hakim Mohammed',13,'MID',39,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Samuel Boateng Fosu',13,'MID',37,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Tahir Mensah',13,'FWD',NULL,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Junior Yeboah',13,'FWD',19,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Eric Wiafe Darkwah',13,'FWD',32,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Kweku Baffoe',13,'FWD',7,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Rudolf Mensah',13,'FWD',11,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Benjamin York',13,'FWD',NULL,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Andrews Quainoo',13,'FWD',NULL,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Godfred Quaye',13,'FWD',33,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Martin Gyan',13,'FWD',40,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Emmanuel Essoun',13,'FWD',NULL,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Rabin Ousmane Sanon',11,'GK',16,NULL,'AVAILABLE','Burkina Faso');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Abraham Odonkor',11,'GK',1,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Lawrence Ansah',11,'GK',66,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Hadina Bariu',11,'GK',99,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Mac-Williams Boateng',11,'DEF',88,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Stephan Agyenim Ivan',11,'DEF',NULL,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Razak Simpson',11,'DEF',30,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Raymond Oko Grippman',11,'DEF',13,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Suleman Yahaya Abu',11,'DEF',NULL,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Asante Boahen',11,'DEF',5,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Michael Abrokwa',11,'DEF',12,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Aaron Quartey',11,'DEF',22,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Nathaniel Anertey Abbey',11,'DEF',26,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Kwame Boakye',11,'DEF',14,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Isaac Asare',11,'DEF',43,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Brandon Antwi Sarpong',11,'MID',40,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Kelvin Ampoful',11,'MID',69,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Joseph Effah',11,'MID',80,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Isaac Botchway',11,'MID',6,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Ridwan Yahaya',11,'MID',7,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Abdela Mashud',11,'MID',20,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Evans Sarfo',11,'MID',28,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Prince Acquah',11,'MID',NULL,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Emmanuel Akesseh',11,'MID',NULL,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Yussif Alhassan Chibsah',11,'MID',31,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Emmanuel Boahene',11,'MID',29,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Sulemana Suhuyini',11,'MID',8,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Emmanuel Annor',11,'FWD',33,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Richard Danso',11,'FWD',10,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Alex Aso',11,'FWD',2,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Andrews Cobbinah',11,'FWD',11,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Faruk Mohammed',11,'FWD',NULL,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Victor Quarshie',11,'FWD',9,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('John Ahuma Ocansey',11,'FWD',25,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Martin Akolgo',11,'FWD',27,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Aryeetey Ayikwei',11,'FWD',35,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Wilt Commodore',11,'FWD',41,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Abdul Rashid Maama Laryea',11,'FWD',NULL,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Kweku Musah',10,'GK',16,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Kwesi Nketia',10,'GK',1,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Daniel Amissah',10,'GK',40,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Safianu Usman',10,'DEF',5,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('John Alossode',10,'DEF',18,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Courage Gbeve',10,'DEF',35,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Paul Kwame',10,'DEF',21,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Alkassim Mohammed Haruna',10,'DEF',24,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Solomon Adomako',10,'DEF',32,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Prince Amevor',10,'DEF',2,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Justice Dikro-Adiabo',10,'DEF',4,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Yussif Salifu',10,'DEF',13,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Emmanuel Kyeremeh',10,'DEF',15,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Maxwell Agyemang',10,'DEF',25,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Mohamed Bangoura',10,'DEF',30,NULL,'AVAILABLE','Guinea');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Patrick Amartey',10,'DEF',12,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Kekeli Attor',10,'DEF',44,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Kwadwo Boamah',10,'MID',10,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Sena Ati',10,'MID',11,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Daniel Osei Senior',10,'MID',28,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Obeng Richard',10,'MID',6,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Bernard Okine',10,'MID',8,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Francis Odoom',10,'MID',17,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Hamidu Abdulai',10,'MID',20,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Richard Mccharthy',10,'MID',23,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Ebenezer Armegah',10,'MID',49,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Michael Yeboah',10,'MID',7,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Stephen Diyou',10,'FWD',70,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Ganiu Abass',10,'FWD',9,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Lawson Bekui',10,'FWD',77,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Richard Gadze',10,'FWD',43,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('William Oduro',10,'FWD',37,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Daniel Osafo',10,'FWD',19,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Anane Keke David',10,'FWD',29,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Alhassan Adamu',10,'FWD',33,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Joseph Baah',17,'GK',21,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Hardy Obenfo Adjei',17,'GK',13,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Stephen Ampaabeng',17,'GK',22,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Kenneth Boakye Owusu',17,'DEF',3,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Edmund Afurapoe',17,'DEF',24,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Desmond Achampong',17,'DEF',27,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Jibril Muhammed',17,'DEF',NULL,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Farouk Ameyaw',17,'DEF',2,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Hakem Milla',17,'DEF',6,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Hamza Musah',17,'DEF',33,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Solomon Yeboah Korsah',17,'DEF',20,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Kwayie Simms',17,'DEF',NULL,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Samuel Acquah',17,'DEF',NULL,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Joseph Dwomoh',17,'DEF',26,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Felix Akorlor',17,'DEF',17,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Ahmed Issah',17,'DEF',30,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Eden Kofi Asamoah',17,'MID',12,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Mohammed Issah',17,'MID',4,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Boateng Emmanuel',17,'MID',10,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Mathew Amponsah',17,'MID',23,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Ephraim Oduro',17,'MID',5,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Angel Ewulla',17,'MID',15,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('McDennis Dotse',17,'MID',25,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Ibrahim Asante Zakari',17,'MID',28,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Francis Simon',17,'MID',29,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Festus Nkrumah',17,'MID',32,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Obed Ofori',17,'MID',37,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Desmond Tetteh',17,'MID',50,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('George Osei Amponsah',17,'MID',NULL,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Osman Zackaria',17,'FWD',11,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Daniel Lomotey',17,'FWD',9,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Ebrahim Hodu',17,'FWD',7,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Rauf Munah',17,'FWD',18,NULL,'AVAILABLE','Ghana');
INSERT INTO players(full_name,club_id,position,jersey_number,photo_url,status,nationality) VALUES ('Torxo Atsu',17,'FWD',40,NULL,'AVAILABLE','Ghana');
