-- Backs the Premium subscription feature (Paystack-funded). One row per
-- user represents their CURRENT subscription state (fast "is this user
-- premium" lookups); `payments` is the full transaction history that state
-- is derived from.
CREATE TABLE subscriptions (
    id SERIAL PRIMARY KEY,
    user_id INT NOT NULL UNIQUE REFERENCES users(id) ON DELETE CASCADE,
    status VARCHAR(20) NOT NULL DEFAULT 'INACTIVE',
    plan VARCHAR(30) NOT NULL DEFAULT 'PREMIUM_MONTHLY',
    started_at TIMESTAMP WITHOUT TIME ZONE,
    expires_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT now()
);

CREATE TABLE payments (
    id SERIAL PRIMARY KEY,
    user_id INT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    -- Paystack transaction reference - generated by us, sent to Paystack on
    -- initialize, and used to look the transaction back up on verify/webhook.
    reference VARCHAR(100) NOT NULL UNIQUE,
    -- Paystack amounts are in the currency's smallest subunit (pesewas for
    -- GHS, i.e. GH1 = 100) - stored as-sent so verify can cross-check it.
    amount_pesewas INT NOT NULL,
    currency VARCHAR(10) NOT NULL DEFAULT 'GHS',
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT now(),
    verified_at TIMESTAMP WITHOUT TIME ZONE
);

CREATE INDEX idx_payments_user ON payments(user_id);
CREATE INDEX idx_payments_reference ON payments(reference);
